name: Build APK and Copy to myapk Folder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: $HOME/Android/Sdk
      PATH: $ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
      JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.13-11/x64

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install unzip
      run: sudo apt-get update && sudo apt-get install -y unzip

    - name: Install tar
      run: sudo apt-get install -y tar

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
        unzip -q commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
        rm commandlinetools.zip
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

    - name: Accept Licenses and Install SDK
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK with Gradle
      run: ./gradlew clean assembleRelease

    - name: Create myapk Folder
      run: mkdir -p myapk

    - name: Copy APK to myapk Folder
      run: cp app/build/outputs/apk/release/app-release.apk myapk/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: myapk/app-release.apk
