name: Build APK and Copy to myapk Folder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK Command Line Tools
      run: |
        # Create the SDK directory
        mkdir -p $HOME/Android/Sdk/cmdline-tools

        # Download and unzip the command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/Android/Sdk/cmdline-tools
        rm commandlinetools.zip

        # Move the extracted folder to "latest" (to comply with sdkmanager structure)
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest

        # Accept licenses and install necessary packages
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --update

        # Install platform-tools, build-tools, and SDK platforms
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Unset ANDROID_SDK_ROOT if set
      run: |
        unset ANDROID_SDK_ROOT

    - name: Set ANDROID_HOME environment variable
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/platform-tools:$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Make gradlew executable
      run: |
        chmod +x ./gradlew

    - name: Build APK with Gradle
      run: |
        ./gradlew clean assembleRelease

    - name: Create myapk Folder
      run: |
        mkdir -p myapk

    - name: Copy APK to myapk Folder
      run: |
        cp app/build/outputs/apk/release/app-release.apk myapk/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: myapk/app-release.apk
