name: Build APK and Copy to myapk Folder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Ensure Temurin is used instead of AdoptOpenJDK

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/Android/Sdk
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools.zip
        unzip commandlinetools.zip -d $HOME/Android/Sdk
        rm commandlinetools.zip
        yes | $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --licenses
        $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager --update
        # Install essential Android SDK components including adb
        $HOME/Android/Sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build APK with Gradle
      run: |
        ./gradlew clean assembleRelease

    - name: Create myapk Folder
      run: |
        mkdir -p myapk

    - name: Copy APK to myapk Folder
      run: |
        cp app/build/outputs/apk/release/app-release.apk myapk/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: myapk/app-release.apk
